version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: xo
    versions:
    - 0.36.1
  - dependency-name: mocha
    versions:
    - 8.2.1
  - dependency-name: superstruct
    versions:
    - 0.13.1
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.0.6
